### PR TITLE
Fix issues found when trying to run cache on my set of bundles

### PR DESCRIPTION
**Pull request by forivall**
PR for patches stated in zsh-users#129

### CODE REVIEW

**Comment by forivall** [comment]
Please, use english, not memes.

**Comment by desyncr** [comment]
What is a meme?

**Comment by forivall** [comment]
Fuck it, I switched to zgen. It's just as fast as my tweaks, already has a cache that's smart and doesn't do overly complex bullshit just to save 10ms, and I don't have to deal with this asshole memester.

**Comment by desyncr** [comment]
Don't let the door hit you on the way out :+1:

**Pull request closed without merging**
